dist: trusty
sudo: required
language: node_js
node_js:
  - 12

before_script:
  - npm install -g @angular/cli
script:
- ng lint
- ng build --prod 

before_deploy:
  - npm run --prod build
  - echo -e "node_modules\npackage-lock.json" > .gitignore

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
